# Generated by Django 5.2.8 on 2025-11-13 00:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import project.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_fixed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Custo Fixo')),
                ('physical_margin', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, verbose_name='Margem Física Padrão (%)')),
                ('shopee_commission', models.DecimalField(decimal_places=2, default=Decimal('14.00'), max_digits=5, verbose_name='Comissão Shopee (%)')),
                ('free_shipping_fee', models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=5, verbose_name='Programa Frete Grátis (%)')),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=8, verbose_name='Taxa Fixa (R$)')),
                ('highlight_active', models.BooleanField(default=True, verbose_name='Campanha Destaque Ativa?')),
                ('highlight_fee', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5, verbose_name='Taxa Campanha Destaque (%)')),
            ],
            options={
                'verbose_name': 'Configuração de Taxas',
                'verbose_name_plural': 'Configurações de Taxas',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('document', models.CharField(blank=True, max_length=40, verbose_name='documento (CNPJ/CPF)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=60, unique=True, verbose_name='código do produto')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='preço de custo')),
                ('recommended_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='preço recomendado')),
                ('negotiation_margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='margem de negociação (%)')),
                ('stock', models.IntegerField(default=0, verbose_name='estoque')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('video_file', models.FileField(blank=True, null=True, upload_to=project.models.product_video_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm', 'mkv'])], verbose_name='vídeo (opcional)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='project.supplier')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=project.models.product_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='imagem')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='texto alternativo')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='posição')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.product')),
            ],
            options={
                'verbose_name': 'Imagem do produto',
                'verbose_name_plural': 'Imagens dos produtos',
                'ordering': ['position', 'created_at'],
                'unique_together': {('product', 'position')},
            },
        ),
    ]
