# Generated by Django 5.2.8 on 2025-11-13 23:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_vendor_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade Vendida')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Total da Venda')),
                ('platform', models.CharField(choices=[('loja_fisica', 'Loja Física'), ('shopee', 'Shopee'), ('outros', 'Outros')], default='loja_fisica', max_length=20, verbose_name='Plataforma de Venda')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Venda')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='project.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-sale_date'],
            },
        ),
    ]
