# Generated by Django 5.2.8 on 2025-11-13 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='project.vendor', verbose_name='Vendedor'),
        ),
    ]
