# Generated by Django 5.2.8 on 2025-11-14 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_sale_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField(verbose_name='Alteração no Estoque')),
                ('reason', models.CharField(choices=[('new_stock', 'Novo Estoque'), ('sale', 'Venda'), ('manual_adjustment', 'Ajuste Manual'), ('initial_stock', 'Estoque Inicial')], max_length=20, verbose_name='Motivo')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='project.product')),
            ],
            options={
                'verbose_name': 'Histórico de Estoque',
                'verbose_name_plural': 'Históricos de Estoque',
                'ordering': ['-timestamp'],
            },
        ),
    ]
